# -*- coding: utf-8 -*-
"""preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UbpytjkDoGlDMGurcke2LrxGaZENN4Ej
"""

import gc
import os
import shutil

print("Initiating ChromaDB cleanup...")

# 1. Delete active client and collection objects from memory
try:
    del client
    del text_collection
    del image_collection
except NameError:
    # Variables don't exist in this session, which is perfectly fine
    pass

# 2. Force garbage collection to release SQLite file locks
gc.collect()
print("✅ Memory and file locks released.")

# 3. Completely wipe the existing database folder (Optional but recommended for a fresh start)
# Make sure this matches the path where you save your Colab database!..

db_path = "chroma_db"

if os.path.exists(db_path):
    # This recursively deletes the folder and all its contents (including .wal and .lock files)
    shutil.rmtree(db_path)
    print(f"🗑️ Permanently deleted the old database at '{db_path}'.")
else:
    print(f"ℹ️ Directory '{db_path}' was not found.")

print("🚀 Cleanup complete! You are ready to initialize a brand new database.")

# Step 1: Install requirements
!pip install langchain langchain-community langchain-google-genai chromadb transformers torch torchvision torchaudio pillow google-genai

# Step 2: Import libraries
import os
import json
import time
import gc
from pathlib import Path
from PIL import Image
import torch
from transformers import CLIPProcessor, CLIPModel
from langchain_text_splitters import RecursiveCharacterTextSplitter
import chromadb
import chromadb.utils.embedding_functions as embedding_functions

print("Libraries installed successfully!")

# Step 3: Mount Drive
from google.colab import drive
drive.mount('/content/drive')

# Set project path
PROJECT_PATH = '/content/drive/MyDrive/data'
os.chdir(PROJECT_PATH)
print("Working directory:", PROJECT_PATH)

# Step 4: Set Gemini API Key
import getpass
GEMINI_API_KEY = getpass.getpass("Enter your Gemini API Key: ")
os.environ["GEMINI_API_KEY"] = GEMINI_API_KEY

# Step 5: Initialize Models
print("Loading CLIP...")
clip_model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")
clip_processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")

# Initialize Gemini Multimodal Embedding Function
gemini_multimodal_embedding = embedding_functions.GoogleGeminiEmbeddingFunction(
    model_name="gemini-embedding-2-preview"
)
print("✅ Multimodal Gemini Embedding function initialized!")

def get_clip_embedding(image_path):
    """Generate CLIP embedding for image using T4 GPU."""
    try:
        image = Image.open(image_path).convert("RGB")
        device = "cuda" if torch.cuda.is_available() else "cpu"
        clip_model.to(device)
        inputs = clip_processor(images=image, return_tensors="pt").to(device)

        with torch.no_grad():
            outputs = clip_model.get_image_features(**inputs)

        if hasattr(outputs, 'image_embeds'):
            image_features = outputs.image_embeds
        elif hasattr(outputs, 'pooler_output'):
            image_features = outputs.pooler_output
        else:
            image_features = outputs

        embedding = image_features.cpu().numpy()[0]
        return embedding.tolist()

    except Exception as e:
        print(f"Error processing {image_path}: {e}")
        return None

# Step 7: Populate Vector Database
def populate_multimodal_rag():
    client = chromadb.PersistentClient(path="chroma_db")

    # [FIX APPLIED HERE]: Added the embedding_function parameter to ensure
    # Gemini is actually used to embed the text chunks.
    text_collection = client.get_or_create_collection(
        name="sri_lankan_recipes_text",
        embedding_function=gemini_multimodal_embedding
    )

    # Image collection stays as is, using pre-computed raw CLIP vectors
    image_collection = client.get_or_create_collection(
        name="sri_lankan_recipes_images"
    )

    print("Loading recipes and images...")
    recipes_dir = Path("recipes/processed")
    images_dir = Path("images")

    text_splitter = RecursiveCharacterTextSplitter(chunk_size=800, chunk_overlap=100)
    records_added = 0

    for json_file in recipes_dir.glob("*.json"):
        try:
            with open(json_file, encoding='utf-8') as f:
                recipe = json.load(f)
                dish_name = recipe.get('dish_name')

                ingredients_str = "\n".join([f"- {ing['name']}" for ing in recipe.get('ingredients', [])])
                recipe_text = f"Dish Name: {dish_name}\nDescription: {recipe.get('description', '')}\nIngredients:\n{ingredients_str}"

                dish_image_folder = images_dir / dish_name.replace(" ", "_").lower()

                if dish_image_folder.exists():
                    img_files = list(dish_image_folder.glob("*.jpg"))
                    chunks = text_splitter.split_text(recipe_text)

                    # A. Ingest Text Chunks
                    for chunk_idx, chunk in enumerate(chunks):
                        text_id = f"{dish_name.replace(' ', '_').lower()}_text_chunk_{chunk_idx}"
                        text_collection.add(
                            ids=[text_id],
                            documents=[chunk],
                            metadatas=[{"dish_name": dish_name, "source": "recipe_text"}]
                        )
                        records_added += 1
                        time.sleep(0.05)

                    # B. Ingest Images utilizing CLIP
                    for img_idx, img_file in enumerate(img_files):
                        image_id = f"{dish_name.replace(' ', '_').lower()}_image_{img_idx}"
                        image_vector = get_clip_embedding(str(img_file))

                        if image_vector is None:
                            print(f"⚠️ Skipping image due to empty embedding: {img_file}")
                            continue

                        image_collection.add(
                            ids=[image_id],
                            embeddings=[image_vector],
                            metadatas=[{
                                "dish_name": dish_name,
                                "source": "recipe_image",
                                "image_path": str(img_file)
                            }]
                        )
                        records_added += 1
                        time.sleep(0.05)

                else:
                    print(f"Warning: No image folder found for {dish_name}")

        except Exception as e:
            print(f"Error processing {json_file.name}: {e}")

    print(f"\n✅ SUCCESS! Multimodal RAG ready with {records_added} total elements synced inside /chroma_db.")

# Execute clean data stream
populate_multimodal_rag()