"""
schemas/scan.py — Request & Response models for the /scan endpoint.

Pydantic v2 models give automatic validation and clear OpenAPI docs.
"""

from __future__ import annotations

from typing import Any, Optional
from pydantic import BaseModel, Field


# --------------------------------------------------------------------------- #
#  Request                                                                     #
# --------------------------------------------------------------------------- #

class ScanRequest(BaseModel):
    """
    Body sent alongside the image upload.
    user_allergens: list of allergens the user has selected in their profile.
    Example: ["gluten", "shellfish", "nuts"]
    """
    user_allergens: list[str] = Field(
        default=[],
        description="Allergen categories selected by the user.",
        example=["gluten", "shellfish", "tree_nuts"],
    )


# --------------------------------------------------------------------------- #
#  Nested Response models                                                      #
# --------------------------------------------------------------------------- #

class AllergenMatch(BaseModel):
    """Details of a single allergen trigger found in the dish."""
    allergen_category: str = Field(description="Top-level allergen category (e.g. 'shellfish').")
    triggered_by: list[str] = Field(description="Ingredient(s) that caused this match.")
    source: str = Field(description="How the allergen was detected: 'rule_based' | 'llm' | 'user_profile'.")


class ClinicalAlert(BaseModel):
    """A single clinical risk prediction from the ML model for one ingredient."""
    ingredient: str = Field(description="Ingredient name that triggered the clinical alert.")
    model_key: str = Field(description="Sanitised file-stem used to locate the joblib model.")
    risk_level: int = Field(description="Predicted risk level: 1 = elevated (binary classifier output).")
    confidence: str = Field(description="Probability score from the model (e.g. '87.3%').")
    msg: str = Field(description="Human-readable clinical risk message.")


class SafetyNetWarning(BaseModel):
    """A cross-reactivity warning generated by an Apriori association rule."""
    trigger: str = Field(description="Ingredient that fired the Apriori rule.")
    linked_risks: list[str] = Field(description="Co-reactive ingredients associated with the trigger.")
    msg: str = Field(description="Human-readable cross-reactivity warning.")


class MLRiskReport(BaseModel):
    """Complete ML + Apriori risk prediction report for a scanned dish."""
    clinical_alerts: list[ClinicalAlert] = Field(
        default=[],
        description="Per-ingredient risk predictions from the XGBoost SMOTE ML models.",
    )
    safety_net_warnings: list[SafetyNetWarning] = Field(
        default=[],
        description="Cross-reactivity warnings derived from validated Apriori association rules.",
    )
    models_evaluated: int = Field(
        default=0,
        description="Number of ML models successfully run during this prediction.",
    )
    ingredients_checked: int = Field(
        default=0,
        description="Total number of detected ingredients passed through the ML engine.",
    )


class ScanResponse(BaseModel):
    """Full response returned by POST /api/v1/scan."""

    # Vision & RAG results
    identified_dish: str = Field(description="Best-match dish name identified by the system.")
    confidence: str = Field(description="Confidence level: 'high' | 'medium' | 'low'.")
    ingredients: list[str] = Field(description="Ingredient list from the matched recipe.")
    rag_context_used: bool = Field(description="Whether RAG retrieval contributed to the result.")

    # Allergen results
    detected_allergens: list[AllergenMatch] = Field(
        description="All allergens found in the dish."
    )
    is_safe: bool = Field(description="True if no allergens match the user's profile.")
    safety_message: str = Field(description="Human-readable safety summary.")

    # LLM explanation
    llm_explanation: str = Field(
        description="Natural-language explanation from Gemini about the dish and its risks."
    )

    # ML Risk Prediction (Layer 4 — ML + Apriori)
    ml_risk_report: MLRiskReport = Field(
        default_factory=MLRiskReport,
        description="Clinical risk predictions from XGBoost models + Apriori cross-reactivity safety-net.",
    )

    # Optional debug/metadata
    llm_raw_dish_guess: Optional[str] = Field(
        default=None,
        description="Raw dish name guessed by Gemini vision (before RAG refinement)."
    )
